# Generated by Django 5.2.1 on 2025-12-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0132_add_location_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='location_updated_at',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='location_browser_updated_at',
            field=models.DateTimeField(blank=True, help_text='When browser GPS location was last updated', null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='location_ip_updated_at',
            field=models.DateTimeField(blank=True, help_text='When IP-based location was last updated', null=True),
        ),
    ]
