# Generated by Django 5.2.1 on 2025-12-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0015_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='code_snippet',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
